<a href="https://colab.research.google.com/github/UdayRathod5277/ShadowFox/blob/main/BostonHousePrice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error

# New Section

In [ ]:
file_path = "/content/HousingData.csv"
df = pd.read_csv(file_path)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     486 non-null    float64
 1   ZN       486 non-null    float64
 2   INDUS    486 non-null    float64
 3   CHAS     486 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      486 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64
 9   TAX      506 non-null    int64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    486 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB

In [ ]:
df.head(478)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,11.43,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
473,4.64689,0.0,18.10,0.0,0.614,6.980,67.6,2.5329,24,666,20.2,374.68,11.43,29.8
474,8.05579,0.0,18.10,0.0,0.584,5.427,95.4,2.4298,24,666,20.2,352.58,18.14,13.8
475,6.39312,0.0,18.10,0.0,0.584,6.162,97.4,2.2060,24,666,20.2,302.76,24.10,13.3
476,4.87141,0.0,18.10,0.0,0.614,6.484,93.6,2.3053,24,666,20.2,396.21,18.68,16.7
477,15.02340,0.0,18.10,0.0,0.614,5.304,97.3,2.1007,24,666,20.2,349.48,24.91,12.0

In [ ]:
df.fillna(df.median(), inplace=True)

In [ ]:
X = df.drop(columns=["MEDV"])
y = df["MEDV"]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
y_pred

array([ 2.90229076e+01,  3.65165445e+01,  1.45393017e+01,  2.50600581e+01,
        1.83967266e+01,  2.30288828e+01,  1.79671579e+01,  1.45828295e+01,
        2.20828043e+01,  2.08561812e+01,  2.51163978e+01,  1.85615496e+01,
       -5.65346810e+00,  2.17307279e+01,  1.90724377e+01,  2.59110845e+01,
        1.96745390e+01,  5.82734420e+00,  4.08961762e+01,  1.71863926e+01,
        2.53685702e+01,  3.02269659e+01,  1.17956763e+01,  2.35052226e+01,
        1.73202890e+01,  1.50842857e+01,  2.16408155e+01,  1.45043809e+01,
        2.28135918e+01,  1.94256178e+01,  2.25511025e+01,  2.52307392e+01,
        2.55426783e+01,  1.66458528e+01,  1.63916994e+01,  1.66977211e+01,
        3.11293531e+01,  2.02733495e+01,  2.43791078e+01,  2.31362096e+01,
        1.44904686e+01,  3.23022632e+01,  4.29155975e+01,  1.76345789e+01,
        2.76271693e+01,  1.63930624e+01,  1.42626808e+01,  2.61233033e+01,
        1.97094146e+01,  3.01725122e+01,  2.10197700e+01,  3.36926419e+01,
        1.64026207e+01,  2.63810130e+01,  3.97591557e+01,  2.19985134e+01,
        1.83602943e+01,  3.27373371e+01,  2.53946712e+01,  1.28353315e+01,
        2.27567582e+01,  3.06706217e+01,  3.17474349e+01,  1.63130492e+01,
        2.03757101e+01,  1.71967555e+01,  2.01187652e+01,  2.61533813e+01,
        3.08691867e+01,  1.14004673e+01,  2.09212060e+01,  2.65411989e+01,
        1.09963913e+01,  1.24867987e+01,  2.37543135e+01,  6.39064666e+00,
        2.16924544e+01,  4.16502168e+01,  1.86194707e+01,  8.85053461e+00,
        2.09871365e+01,  1.31441032e+01,  2.09606516e+01,  9.13888049e+00,
        2.29977817e+01,  3.23927955e+01,  1.93492206e+01,  2.55887641e+01,
        2.86454769e+01,  1.97739456e+01,  2.59693454e+01,  5.78020700e+00,
        1.95226757e+01,  1.52811249e+01,  1.08216355e+01,  2.00912483e+01,
        2.37254625e+01,  2.74671731e-02,  1.35624962e+01,  1.60903141e+01,
        2.27635065e+01,  2.43818077e+01])

In [ ]:
X_train.head(1)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
477,15.0234,0.0,18.1,0.0,0.614,5.304,97.3,2.1007,24,666,20.2,349.48,24.91

In [ ]:
input_data_model = pd.DataFrame([[15.0234,0.0,18.1,0.0,0.614,5.304,97.3,2.1007,24,666,20.2,349.48,24.91]],
    columns=['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT'])

In [ ]:
model.predict(input_data_model)

array([10.65718029])